Repository ruisaraiva19/favycon, pull requests merged in 2020-04, with the labels that each got.

#5 feat: setup next, eslint, stylelint, and typescript
  .eslintrc.json
  .github/renovate.json
  .github/semantic.yml
  .github/workflows/commitlint.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .gitignore
  .huskyrc.json
  .npmrc
  .prettierrc
  .stylelintrc.json
  .vscode/settings.json
  LICENSE
  README.md
  commitlint.config.js
  components/.gitkeep
  hooks/.gitkeep
  lint-staged.config.js
  next-env.d.ts
  next.config.js
  now.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/favicon.ico
  public/zeit.svg
  release.config.js
  styles/main.scss
  tsconfig.json
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#12 feat(styles): add base styles, font, and favicon
  .editorconfig
  components/typography/index.module.scss
  components/typography/index.tsx
  package.json
  pages/index.tsx
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/fonts/Manrope/Manrope-Bold.woff
  public/fonts/Manrope/Manrope-Bold.woff2
  public/fonts/Manrope/Manrope-Medium.woff
  public/fonts/Manrope/Manrope-Medium.woff2
  public/fonts/Manrope/Manrope-Regular.woff
  public/fonts/Manrope/Manrope-Regular.woff2
  public/fonts/Manrope/Manrope-SemiBold.woff
  public/fonts/Manrope/Manrope-SemiBold.woff2
  public/zeit.svg
  styles/font.scss
  styles/main.scss
  styles/reset.scss
  styles/variables.scss
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#18 docs: add contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: Type: Chore, documentation

#20 chore(storybook): add css modules support
  .storybook/main.js
  components/typography/index.stories.tsx
Labels: Status: Ready To Review, Type: Chore

#23 feat(resize): add resize serverless function
  .eslintrc.json
  .gitignore
  package.json
  pages/api/resize.ts
  utils/api.ts
  utils/favicon.ts
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#22 feat: add button component
  .storybook/preview-body.html
  components/button/index.module.scss
  components/button/index.stories.tsx
  components/button/index.tsx
  package.json
  pages/_document.tsx
  public/noflash.js
  tsconfig.json
  yarn.lock
Labels: Status: Changes Requested, Type: Feature

#21 feat: add dark mode toggle component
  .storybook/preview-body.html
  .storybook/webpack.config.js
  .stylelintrc.json
  README.md
  components/dark-mode-toggle/index.module.scss
  components/dark-mode-toggle/index.stories.tsx
  components/dark-mode-toggle/index.tsx
  components/svgs/svg-appycon.tsx
  components/svgs/svg-arrow-down.tsx
  components/svgs/svg-favycon.tsx
  components/svgs/svg-image-upload.tsx
  components/svgs/svg-info.tsx
  components/svgs/svg-moon.tsx
  components/svgs/svg-sun.tsx
  next.config.js
  package.json
  pages/_document.tsx
  tsconfig.json
  utils/ids.ts
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#24 feat(layout): add base page layout
  .storybook/logo.png
  .storybook/preview-body.html
  .storybook/styles.css
  components/base-layout/index.module.scss
  components/base-layout/index.tsx
  components/button/index.module.scss
  components/button/index.stories.tsx
  components/button/index.tsx
  components/dark-mode-toggle/index.module.scss
  components/dark-mode-toggle/index.stories.tsx
  components/dark-mode-toggle/index.tsx
  components/seo/index.tsx
  components/svgs/svg-moon.tsx
  components/svgs/svg-sun.tsx
  components/tool-title/index.module.scss
  components/tool-title/index.stories.tsx
  components/tool-title/index.tsx
  components/typography/index.module.scss
  components/typography/index.stories.tsx
  components/typography/index.tsx
  pages/_document.tsx
  pages/api/favycon.ts
  pages/appycon.tsx
  pages/favycon.tsx
  pages/index.tsx
  public/js/noflash.js
  styles/main.scss
  styles/variables.scss
  tsconfig.json
Labels: Status: Ready To Review, Type: Feature

#25 feat(favycon): add drap and drop component
  .vscode/settings.json
  components/button/index.module.scss
  components/button/index.stories.tsx
  components/drag-and-drop/index.module.scss
  components/drag-and-drop/index.stories.tsx
  components/drag-and-drop/index.tsx
  components/svgs/svg-appycon.tsx
  components/svgs/svg-arrow-down.tsx
  components/svgs/svg-drop-zone.tsx
  components/svgs/svg-favycon.tsx
  components/svgs/svg-image-upload.tsx
  components/svgs/svg-info.tsx
  components/svgs/svg-moon.tsx
  components/svgs/svg-sun.tsx
  components/typography/index.module.scss
  components/typography/index.tsx
  package.json
  styles/main.scss
  styles/variables.scss
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#29 feat(page): add favycon home page
  components/lazy-image/index.module.scss
  components/lazy-image/index.tsx
  components/typography/index.module.scss
  package.json
  pages/appycon.tsx
  pages/favycon.tsx
  pages/index.module.scss
  pages/index.tsx
  public/images/dnd-dark@1x.png
  public/images/dnd-dark@2x.png
  public/images/dnd-light@1x.png
  public/images/dnd-light@2x.png
  public/images/unsplash-1@1x.jpg
  public/images/unsplash-1@2x.jpg
  public/images/unsplash-1@placeholder.jpg
  public/images/unsplash-2@1x.jpg
  public/images/unsplash-2@2x.jpg
  public/images/unsplash-2@placeholder.jpg
  public/images/unsplash-3@1x.jpg
  public/images/unsplash-3@2x.jpg
  public/images/unsplash-3@placeholder.jpg
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#32 feat(seo): add seo meta tags
  components/seo/index.tsx
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/share.png
Labels: Status: Ready To Review, Type: Chore

#39 feat: add drag and drop wizard
  .babelrc
  .github/renovate.json
  .storybook/manager-head.html
  .storybook/styles.css
  README.md
  components/button/index.module.scss
  components/button/index.tsx
  components/checkbox/index.module.scss
  components/checkbox/index.stories.tsx
  components/checkbox/index.tsx
  components/code-highlight/index.module.scss
  components/code-highlight/index.tsx
  components/drag-and-drop/index.module.scss
  components/drag-and-drop/index.stories.tsx
  components/drag-and-drop/index.tsx
  components/favycon-info/index.module.scss
  components/favycon-info/index.tsx
  components/favycon-wizard/index.module.scss
  components/favycon-wizard/index.tsx
  components/header/index.module.scss
  components/header/index.tsx
  components/seo/index.tsx
  components/svgs/svg-appycon.tsx
  components/svgs/svg-arrow-down.tsx
  components/svgs/svg-check.tsx
  components/svgs/svg-checkbox.tsx
  components/svgs/svg-error.tsx
  components/svgs/svg-favycon.tsx
  components/svgs/svg-image-upload.tsx
  components/svgs/svg-info.tsx
  components/svgs/svg-moon.tsx
  components/svgs/svg-sun.tsx
  components/typography/index.module.scss
  components/typography/index.tsx
  package.json
  pages/_document.tsx
  pages/api/favycon.ts
  pages/index.module.scss
  pages/index.tsx
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/fonts/Monaco/Monaco.ttf
  public/share.png
  styles/font.scss
  styles/main.scss
  styles/nprogress.scss
  styles/prism.scss
  styles/variables.scss
  utils/favicon.ts
  utils/files.ts
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#43 chore: release
  .babelrc
  .github/renovate.json
  .storybook/manager-head.html
  .storybook/styles.css
  README.md
  components/button/index.module.scss
  components/button/index.tsx
  components/checkbox/index.module.scss
  components/checkbox/index.stories.tsx
  components/checkbox/index.tsx
  components/code-highlight/index.module.scss
  components/code-highlight/index.tsx
  components/drag-and-drop/index.module.scss
  components/drag-and-drop/index.stories.tsx
  components/drag-and-drop/index.tsx
  components/favycon-info/index.module.scss
  components/favycon-info/index.tsx
  components/favycon-wizard/index.module.scss
  components/favycon-wizard/index.tsx
  components/header/index.module.scss
  components/header/index.tsx
  components/seo/index.tsx
  components/svgs/svg-appycon.tsx
  components/svgs/svg-arrow-down.tsx
  components/svgs/svg-check.tsx
  components/svgs/svg-checkbox.tsx
  components/svgs/svg-error.tsx
  components/svgs/svg-favycon.tsx
  components/svgs/svg-image-upload.tsx
  components/svgs/svg-info.tsx
  components/svgs/svg-moon.tsx
  components/svgs/svg-sun.tsx
  components/typography/index.module.scss
  components/typography/index.tsx
  package.json
  pages/_document.tsx
  pages/api/favycon.ts
  pages/index.module.scss
  pages/index.tsx
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/fonts/Monaco/Monaco.ttf
  public/share.png
  styles/font.scss
  styles/main.scss
  styles/nprogress.scss
  styles/prism.scss
  styles/variables.scss
  utils/favicon.ts
  utils/files.ts
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#49 feat(favycon): add about us modal
  components/button/index.module.scss
  components/button/index.tsx
  components/dark-mode-toggle/index.module.scss
  components/dark-mode-toggle/index.tsx
  components/drag-and-drop/index.module.scss
  components/drag-and-drop/index.tsx
  components/favycon-info/index.module.scss
  components/favycon-info/index.tsx
  components/favycon-wizard/index.module.scss
  components/favycon-wizard/index.tsx
  components/header/index.module.scss
  components/header/index.tsx
  components/lazy-image/index.tsx
  components/seo/index.tsx
  components/svgs/svg-drop-zone.module.scss
  components/svgs/svg-drop-zone.tsx
  components/svgs/svg-image-upload.module.scss
  components/svgs/svg-image-upload.tsx
  components/svgs/svg-info.module.scss
  components/svgs/svg-info.tsx
  components/svgs/svg-twitter.tsx
  components/typography/index.module.scss
  components/typography/index.tsx
  pages/_document.tsx
  public/browserconfig.xml
  public/favicon-114x114.png
  public/favicon-120x120.png
  public/favicon-144x144.png
  public/favicon-150x150.png
  public/favicon-152x152.png
  public/favicon-16x16.png
  public/favicon-180x180.png
  public/favicon-192x192.png
  public/favicon-310x310.png
  public/favicon-32x32.png
  public/favicon-57x57.png
  public/favicon-60x60.png
  public/favicon-70x70.png
  public/favicon-72x72.png
  public/favicon-76x76.png
  public/favicon-96x96.png
  public/images/people/aNyTh1nGeDuArDo@1x.png
  public/images/people/aNyTh1nGeDuArDo@2x.png
  public/images/people/aboutaugusto@1x.png
  public/images/people/aboutaugusto@2x.png
  public/images/people/rgllm@1x.png
  public/images/people/rgllm@2x.png
  public/images/people/ruisaraiva19@1x.png
  public/images/people/ruisaraiva19@2x.png
  public/js/onload.js
  styles/main.scss
  styles/variables.scss
Labels: Status: Ready To Review, Type: Feature
